### PR TITLE
Update Go vendoring

### PR DESCRIPTION
**Pull request by SuperQ**
* Update to latest upstream Go modules.
* Replace deprecated Prometheus common/log with common/promlog.

Signed-off-by: SuperQ <superq@gmail.com>

### CODE REVIEW

**Comment by Dev25** [comment]
Thanks @SuperQ will take a look and merge/cut a release later this week.

**Comment by SuperQ** [comment]
Nice, thanks!

Two questions:
* Would you be able to setup versioned tags?
* Would you be interested in tranferring/converting this to the [prometheus-community](https://github.com/prometheus-community) org? You would keep admin rights over the repo, but it would allow for some of our auto-maintenance work to keep things updated.

**Review by Dev25 — APPROVED** [review]

**Comment by Dev25** [comment]
That sounds reasonable, i would be happy to do that. After transferring i guess a follow up PR can update CI to start pushing releases to the prometheuscommunity registries and mimic other common exporter CI steps?

**Comment by SuperQ** [comment]
Yes, we usually do a bit of tooling and code conversion to make exporters use similar styles of things like docs, flag handling, etc.

Although, one of the things I've been looking into is to make the normal `memcached_exporter` also handle mcrouter. I see this codebase handles all of the memcache protocol, where the exporter uses a dedicated library.

**Comment by Dev25** [comment]
@SuperQ just wanted to follow up and see if there was still interest in moving this to prometheus-community?

**Pull request merged**
