### PR TITLE
WIP: Mcrouter v39 and greater new metrics

### PR DESCRIPTION
**Pull request by TopeltR**
This pull request aims to fix some of the metric changes introduced in the v39 and above versions of Mcrouter. https://github.com/facebook/mcrouter/commit/c1d34c98b4c2c6f8558364bb990bd07fb3770e09

Note: This pull request is a WIP

### CODE REVIEW

**Comment by xhtdevil** [comment]
Can we merge this to fix the metric naming bug? @SuperQ @Dev25 @sagikazarmark

**Comment by sagikazarmark** [comment]
I'm not a maintainer of this repo. Couple things that certainly have to be done in order to merge it though:

- Resolve conflicts
- Actually finish the PR (it says it's WIP)
- Get rid of unnecessary files (old_metrics, new_metrics)

**Comment by Dev25** [comment]
Yep this PR is still a WIP, it seems that the original author has gone inactive on GitHub. I can clean it up and get it in a usable state but will take a couple weeks to get around to it.

**Comment by xhtdevil** [comment]
Any update on this? @Dev25

**Comment by Dev25** [comment]
> Any update on this? @Dev25

This is now done via #26, thanks to @nziebart. 
Can be found on the quay registry, will fix the github ghcr.io registry and cut a new release soon.

quay.io/dev25/mcrouter_exporter:master-baded3b537723c0f3f9b35f1db2e15fa0369af0c

**Pull request closed without merging**
